//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложение_Курсача
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LaborExchangeEntities : DbContext
    {
        private static LaborExchangeEntities _context;
        public LaborExchangeEntities()
            : base("name=LaborExchangeEntities")
        {
        }

        public static LaborExchangeEntities GetContext()
        {
            if (_context == null)
                _context = new LaborExchangeEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auth> Auth { get; set; }
        public virtual DbSet<Citizen> Citizen { get; set; }
        public virtual DbSet<Vacancies> Vacancies { get; set; }
    
        public virtual ObjectResult<GetDecryptLoginAndPassword_Result> GetDecryptLoginAndPassword()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDecryptLoginAndPassword_Result>("GetDecryptLoginAndPassword");
        }
    }
}
