//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложение_Курсача
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancies
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int NumberOfPlaces { get; set; }
        public string RequeredEdications { get; set; }
        public string Schedule { get; set; }
        public bool Status { get; set; }
        public string Address { get; set; }
        public string Sallary { get; set; }
    }
}
